### ISSUE TITLE
got NoneType:

### ISSUE THREAD

**Issue by EdddieZhong** [HenryLiangzy/thebox_toolkit#2]
Hi there, I got an issue, could you please help me to have a look at it?

I think my env is satisfied.(shown below) 
```
(base) eddiezhong@192-168-1-116 thebox_toolkit % python3 -m pip install -r requirement                        
Requirement already satisfied: requests in /Users/eddiezhong/opt/anaconda3/lib/python3.7/site-packages (from -r requirement (line 1)) (2.24.0)
Requirement already satisfied: beautifulsoup4 in /Users/eddiezhong/opt/anaconda3/lib/python3.7/site-packages (from -r requirement (line 2)) (4.9.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/eddiezhong/opt/anaconda3/lib/python3.7/site-packages (from requests->-r requirement (line 1)) (2020.6.20)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/eddiezhong/opt/anaconda3/lib/python3.7/site-packages (from requests->-r requirement (line 1)) (1.25.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/eddiezhong/opt/anaconda3/lib/python3.7/site-packages (from requests->-r requirement (line 1)) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /Users/eddiezhong/opt/anaconda3/lib/python3.7/site-packages (from requests->-r requirement (line 1)) (2.10)
Requirement already satisfied: soupsieve>1.2 in /Users/eddiezhong/opt/anaconda3/lib/python3.7/site-packages (from beautifulsoup4->-r requirement (line 2)) (2.0.1)
(base) eddiezhong@192-168-1-116 thebox_toolkit % python3 thebox.py https://webcms3.cse.unsw.edu.au/COMP9444/20T3/resources/51718
[14:55:38] Getting the source page... Done!
Traceback (most recent call last):
  File "thebox.py", line 206, in <module>
    main()
  File "thebox.py", line 176, in main
    title, video_list = extract_video_link(html_data.text)
  File "thebox.py", line 138, in extract_video_link
    title = body.header.get_text()
AttributeError: 'NoneType' object has no attribute 'get_text'
```
That is it, Thank you for doing such a great branch

**Comment by arpitmathur1** [comment]
The link should look like: https://thebox.unsw.edu.au/.....................
You can find that below the video.. try to do a ctrl+F and then enter "thebox"

**Comment by HenryLiangzy** [comment]
@arpitmathur1 is already answered your question, and the way to find thebox link is from WebCMS.
For example, base on the link given by you, in the right upper corner there is a button called "View in browser", right-click it and copy the address from the browser, or you can open it in the new page then copy it from the address bar, depends on you. 
I will consider adding the Error hint inside the script, thanks for your remind.

**Comment by EdddieZhong** [comment]
> The link should look like: https://thebox.unsw.edu.au/.....................
> You can find that below the video.. try to do a ctrl+F and then enter "thebox"

Oh My God, what a silly question I have asked!
Thank you so much for all the patience!

**Comment by EdddieZhong** [comment]
> @arpitmathur1 is already answered your question, and the way to find thebox link is from WebCMS.
> For example, base on the link given by you, in the right upper corner there is a button called "View in browser", right-click it and copy the address from the browser, or you can open it in the new page then copy it from the address bar, depends on you.
> I will consider adding the Error hint inside the script, thanks for your remind.

I got it right now, I am too shame to respond to you....
And Thank you for replying to me!
BTW, thank you for making our study and life easier!
